//tealium universal tag - utag.43 ut4.0.202606020148, Copyright 2026 Tealium.com Inc. All Rights Reserved.
try{(function(id,loader){var u={};utag.o[loader].sender[id]=u;if(utag===undefined){utag={};}if(utag.ut===undefined){utag.ut={};}if(utag.ut.loader===undefined){u.loader=function(o){var a,b,c,l;a=document;if(o.type==="iframe"){b=a.createElement("iframe");b.setAttribute("height","1");b.setAttribute("width","1");b.setAttribute("style","display:none");b.setAttribute("src",o.src);}else if(o.type==="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";b.src=o.src;}if(o.id){b.id=o.id;}if(typeof o.cb==="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb();},false);}else{b.onreadystatechange=function(){if(this.readyState==="complete"||this.readyState==="loaded"){this.onreadystatechange=null;o.cb();}};}}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l==="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b);}}};}else{u.loader=utag.ut.loader;}
u.ev={'view':1,"link":1};u.id='utag_43';u.styleRequested=false;u.scriptRequested=false;u.initialized=false;u.map={"libSalesforceChatDeploymentFolder":"deploymentFolder","libSalesforceChatQueueType":"queueType","libSalesforceChatDelay":"chatDelay","libSalesforceChatDisabled":"chatDisabled","libSalesforceChatNoLoadConfig":"chatNoLoadConfig"};u.extend=[function(a,b,c,d,e,f,g){if(1){d=b['ut.env'];if(typeof d=='undefined')return;c=[{'prod':'Prod'},{'qa':'Staging'}];var m=false;for(e=0;e<c.length;e++){for(f in utag.loader.GV(c[e])){if(d.toString().indexOf(f)>-1){b['libSalesforceChatDeploymentFolder']=c[e][f];m=true};};if(m)break};if(!m)b['libSalesforceChatDeploymentFolder']='Staging';}},function(a,b){try{if((typeof b['libSalesforceChatQueueType']!='undefined'&&b['libSalesforceChatQueueType'].toString().toLowerCase()=='candidateChat'.toLowerCase())||(typeof b['libSalesforceChatQueueType']!='undefined'&&b['libSalesforceChatQueueType'].toString().toLowerCase()=='smeChat'.toLowerCase())||(typeof b['libSalesforceChatQueueType']!='undefined'&&b['libSalesforceChatQueueType'].toString().toLowerCase()=='salesChat'.toLowerCase())||(typeof b['libSalesforceChatQueueType']!='undefined'&&b['libSalesforceChatQueueType'].toString().toLowerCase()=='contactUsChatBot'.toLowerCase())||(typeof b['libSalesforceChatQueueType']!='undefined'&&b['libSalesforceChatQueueType'].toString().toLowerCase()=='enhancedSMEChat'.toLowerCase())||(typeof b['libSalesforceChatQueueType']!='undefined'&&b['libSalesforceChatQueueType'].toString().toLowerCase()=='enhancedCandidateChat'.toLowerCase())){function showChat(){var assetHost="https://au.seek.com";var lk=document.createElement("link");lk.rel="stylesheet";lk.type="text/css";lk.href=assetHost+"/static/crm/chat/css/"+
b['libSalesforceChatDeploymentFolder']+"/chatStyling.css";document.body.appendChild(lk);var st=document.createElement("script");st.src=assetHost+"/static/crm/chat/js/"+
b['libSalesforceChatDeploymentFolder']+"/"+
b['libSalesforceChatQueueType']+".js";document.body.appendChild(st);window.hasChatWidgetLoaded=true;}
if(!window.hasChatWidgetLoaded){if(b['libSalesforceChatDelay']){var tv=parseInt(b['libSalesforceChatDelay'],10);setTimeout(showChat,tv);}else{showChat();}}}}catch(e){utag.DB(e)}}];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){var c,d,e,f,i;u.data={base_url:"https://www.seek.com.au/static/crm/chat/js/{{folder}}/{{queueType}}}.js",css_url:"https://www.seek.com.au/static/crm/chat/css/chatStyling.css",folder:null,queueType:null,chatDisabled:null,chatNoLoadConfig:null,chatDelay:0,};for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){}};for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.data[e[f]]=b[d];}}}
u.isChatDisabled=function(configs){if(configs){const now=Date.now();for(const cfg of configs){let start=cfg.start;let end=cfg.end;if(typeof start==="string"){start=Date.parse(start);}
if(typeof end==="string"){end=Date.parse(end);}
if(typeof start==="number"&&typeof end==="number"&&start<=now&&now<=end){return true;}}}
return false;};u.loader_cb=function(){u.initialized=true;};u.load_library=function(delaySeconds=0){const delay=parseInt(delaySeconds)*1000;setTimeout(()=>{if(!u.styleRequested){u.styleRequested=true;const lk=document.createElement("link");lk.setAttribute("type","text/css");lk.setAttribute("href","https://www.seek.com.au/static/crm/chat/css/chatStyling.css");lk.setAttribute("rel","stylesheet");lk.setAttribute("id",u.id+"s");document.body.appendChild(lk);}
if(!u.scriptRequested){u.scriptRequested=true;u.loader({"type":"script","src":u.data.full_url,"cb":u.loader_cb,"loc":"script","id":u.id});}},delay);};if(u.data.folder&&u.data.queueType){u.data.full_url=u.data.base_url;u.data.full_url=u.data.full_url.replace("{{folder}}",u.data.folder);u.data.full_url=u.data.full_url.replace("{{queueType}}",u.data.queueType);}
if(u.data.chatDisabled===null){u.data.chatDisabled=u.isChatDisabled(u.data.chatNoLoadConfig);}
if(!u.initialized&&u.data.full_url){if(!u.data.chatDisabled&&u.data.full_url){u.load_library(u.data.chatDelay||0);}}
else{u.loader_cb();}}};utag.o[loader].loader.LOAD(id);})("43","seek.candidate-main");}
catch(error){utag.DB(error);}
